#### Librerias

In [30]:
import pandas as pd
import numpy as np

#### Parametros

In [31]:
PATH_PROJECT = 'C:/Users/vatec/OneDrive/Documentos/Hans/Cursos/5 CODERHOUSE - Data Science II - Machine Learning para la Ciencia de Datos Flex/Material/Proyectos/Template Model Project DS/'

PATH = PATH_PROJECT +'data/processed/'

#### Lectura del archivo

In [32]:
df = pd.read_csv(f'{PATH}dataset_merged.csv')

In [33]:
df.head(3)

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,gender,age,height(cm),...,tartar,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,F,40.0,155.0,...,Y,0.043056,0.041667,0.041667,0.041667,0.043056,0.041667,0.041667,0.041667,0
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,F,40.0,160.0,...,Y,0.005556,0.004167,0.041667,0.041667,0.005556,0.004167,0.041667,0.041667,0
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,M,55.0,170.0,...,N,0.005556,0.005556,0.041667,0.041667,0.005556,0.005556,0.041667,0.041667,1

In [34]:
df.tail(3)

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,gender,age,height(cm),...,tartar,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
49997,27351,NaN,NaN,NaN,NaN,1.958333,2.208333,M,20.0,165.0,...,Y,0.045139,0.045139,0.041667,NaN,0.045139,0.045139,0.041667,NaN,1
49998,27352,NaN,NaN,NaN,NaN,2.583333,4.125000,F,60.0,160.0,...,Y,0.002778,0.002778,0.041667,NaN,0.002778,0.002778,0.041667,NaN,0
49999,27354,NaN,NaN,NaN,NaN,2.750000,5.041667,M,45.0,170.0,...,N,0.045139,0.041667,0.041667,NaN,0.045139,0.041667,0.041667,NaN,1

In [35]:
df.sample(5, random_state=42)

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,gender,age,height(cm),...,tartar,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
33553,41917,6.000000,3.958333,8.375,1.875000,2.500000,5.500000,M,55.0,175.0,...,N,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0
9427,11817,5.208333,3.125000,8.125,2.916667,3.291667,4.250000,F,40.0,160.0,...,Y,0.006250,0.004861,0.041667,0.041667,0.006250,0.004861,0.041667,0.041667,0
199,260,NaN,NaN,NaN,4.250000,2.333333,5.458333,F,40.0,150.0,...,N,0.005556,0.004861,0.041667,0.041667,0.005556,0.004861,0.041667,0.041667,0
12447,15517,5.791667,3.416667,10.625,5.750000,2.750000,6.708333,F,50.0,155.0,...,N,0.043056,0.043056,0.041667,0.041667,0.043056,0.043056,0.041667,0.041667,0
39489,49334,4.375000,2.708333,7.375,4.375000,2.583333,3.916667,F,45.0,150.0,...,Y,0.041667,0.001389,0.041667,0.041667,0.041667,0.001389,0.041667,0.041667,0

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   systolic             49592 non-null  float64
 2   relaxation           49588 non-null  float64
 3   Cholesterol          49390 non-null  float64
 4   triglyceride         49979 non-null  float64
 5   HDL                  49053 non-null  float64
 6   LDL                  49053 non-null  float64
 7   gender               49963 non-null  str
 8   age                  49523 non-null  float64
 9   height(cm)           49587 non-null  float64
 10  weight(kg)           49914 non-null  float64
 11  waist(cm)            49616 non-null  float64
 12  fasting blood sugar  49142 non-null  float64
 13  hemoglobin           49859 non-null  float64
 14  Urine protein        49841 non-null  float64
 15  serum creatinine     38941 non-null  float64
 16  AST                  4248 non-null   float64
 17  ALT                  49678 non-null  float64
 18  Gtp                  49937 non-null  float64
 19  oral                 50000 non-null  str
 20  dental caries        50000 non-null  int64
 21  tartar               50000 non-null  str
 22  eyesight(left)_x     49298 non-null  float64
 23  eyesight(right)_x    49524 non-null  float64
 24  hearing(left)_x      49888 non-null  float64
 25  hearing(right)_x     49779 non-null  float64
 26  eyesight(left)_y     49298 non-null  float64
 27  eyesight(right)_y    49524 non-null  float64
 28  hearing(left)_y      49888 non-null  float64
 29  hearing(right)_y     49779 non-null  float64
 30  target               50000 non-null  int64
dtypes: float64(25), int64(3), str(3)
memory usage: 11.8 MB

In [37]:
df.isna().sum()/df.shape[0]*100 # porcentaje de valores nulos por columna

ID                      0.000
systolic                0.816
relaxation              0.824
Cholesterol             1.220
triglyceride            0.042
HDL                     1.894
LDL                     1.894
gender                  0.074
age                     0.954
height(cm)              0.826
weight(kg)              0.172
waist(cm)               0.768
fasting blood sugar     1.716
hemoglobin              0.282
Urine protein           0.318
serum creatinine       22.118
AST                    91.504
ALT                     0.644
Gtp                     0.126
oral                    0.000
dental caries           0.000
tartar                  0.000
eyesight(left)_x        1.404
eyesight(right)_x       0.952
hearing(left)_x         0.224
hearing(right)_x        0.442
eyesight(left)_y        1.404
eyesight(right)_y       0.952
hearing(left)_y         0.224
hearing(right)_y        0.442
target                  0.000
dtype: float64

In [38]:
df.shape

(50000, 31)

In [39]:
df = df.drop(columns=["AST"])

In [40]:
df = df.fillna(df.mean(numeric_only=True))

In [41]:
df.gender.unique()

<StringArray>
['F', 'M', nan]
Length: 3, dtype: str

In [42]:
random_gender = np.random.choice(["F","M"], size=df["gender"].isnull().sum())

In [43]:
random_gender

array(['F', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'F', 'M',
       'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F',
       'M', 'F', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'F'], dtype='<U1')

In [44]:
df.loc[df["gender"].isnull(),"gender"] = random_gender

In [45]:
df.isna().sum()/df.shape[0]*100 # porcentaje de valores nulos por columna

ID                     0.0
systolic               0.0
relaxation             0.0
Cholesterol            0.0
triglyceride           0.0
HDL                    0.0
LDL                    0.0
gender                 0.0
age                    0.0
height(cm)             0.0
weight(kg)             0.0
waist(cm)              0.0
fasting blood sugar    0.0
hemoglobin             0.0
Urine protein          0.0
serum creatinine       0.0
ALT                    0.0
Gtp                    0.0
oral                   0.0
dental caries          0.0
tartar                 0.0
eyesight(left)_x       0.0
eyesight(right)_x      0.0
hearing(left)_x        0.0
hearing(right)_x       0.0
eyesight(left)_y       0.0
eyesight(right)_y      0.0
hearing(left)_y        0.0
hearing(right)_y       0.0
target                 0.0
dtype: float64

In [46]:
df.head(5)

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,gender,age,height(cm),...,tartar,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
0,0,4.750000,3.041667,8.958333,3.416667,3.041667,5.250000,F,40.0,155.0,...,Y,0.043056,0.041667,0.041667,0.041667,0.043056,0.041667,0.041667,0.041667,0
1,1,4.958333,2.916667,8.000000,4.791667,1.750000,5.291667,F,40.0,160.0,...,Y,0.005556,0.004167,0.041667,0.041667,0.005556,0.004167,0.041667,0.041667,0
2,2,5.750000,3.583333,10.083333,7.583333,2.291667,6.291667,M,55.0,170.0,...,N,0.005556,0.005556,0.041667,0.041667,0.005556,0.005556,0.041667,0.041667,1
3,3,4.166667,2.500000,13.416667,10.583333,1.875000,9.416667,M,40.0,165.0,...,Y,0.045139,0.045139,0.041667,0.041667,0.045139,0.045139,0.041667,0.041667,0
4,4,5.000000,3.083333,7.666667,3.083333,2.583333,4.458333,F,40.0,155.0,...,N,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0

In [47]:
df.ID.nunique()

50000

In [48]:
df.duplicated().sum() # sacar el ID

np.int64(0)

In [49]:
df.index

RangeIndex(start=0, stop=50000, step=1)

In [50]:
df.columns

Index(['ID', 'systolic', 'relaxation', 'Cholesterol', 'triglyceride', 'HDL',
       'LDL', 'gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)',
       'fasting blood sugar', 'hemoglobin', 'Urine protein',
       'serum creatinine', 'ALT', 'Gtp', 'oral', 'dental caries', 'tartar',
       'eyesight(left)_x', 'eyesight(right)_x', 'hearing(left)_x',
       'hearing(right)_x', 'eyesight(left)_y', 'eyesight(right)_y',
       'hearing(left)_y', 'hearing(right)_y', 'target'],
      dtype='str')

In [51]:
df.describe()

,ID,systolic,relaxation,Cholesterol,triglyceride,HDL,LDL,age,height(cm),weight(kg),...,dental caries,eyesight(left)_x,eyesight(right)_x,hearing(left)_x,hearing(right)_x,eyesight(left)_y,eyesight(right)_y,hearing(left)_y,hearing(right)_y,target
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,...,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,26284.994580,5.062688,3.167519,8.206039,5.275309,2.387391,4.791840,44.188155,164.646278,65.877008,...,0.213120,0.028450,0.028276,0.042737,0.042758,0.028450,0.028276,0.042737,0.042758,0.366580
std,16015.070567,0.567825,0.401889,1.506033,2.980229,0.609557,1.698239,12.028283,9.172001,12.817799,...,0.409516,0.023898,0.023940,0.006586,0.006640,0.023898,0.023940,0.006586,0.006640,0.481875
min,0.000000,2.958333,1.666667,2.291667,0.333333,0.166667,0.041667,20.000000,130.000000,30.000000,...,0.000000,0.000694,0.000694,0.041667,0.041667,0.000694,0.000694,0.041667,0.041667,0.000000
25%,12499.750000,4.666667,2.916667,7.166667,3.083333,1.958333,3.833333,40.000000,160.000000,55.000000,...,0.000000,0.005556,0.005556,0.041667,0.041667,0.005556,0.005556,0.041667,0.041667,0.000000
50%,24999.500000,5.000000,3.166667,8.166667,4.500000,2.333333,4.750000,40.000000,165.000000,65.000000,...,0.000000,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.041667,0.000000
75%,40034.250000,5.416667,3.416667,9.125000,6.666667,2.708333,5.625000,55.000000,170.000000,75.000000,...,0.000000,0.043056,0.043056,0.041667,0.041667,0.043056,0.043056,0.041667,0.041667,1.000000
max,55690.000000,10.000000,6.083333,18.541667,41.625000,25.750000,77.500000,85.000000,190.000000,135.000000,...,1.000000,0.381250,0.381250,0.083333,0.083333,0.381250,0.381250,0.083333,0.083333,1.000000

In [52]:
df.oral.unique()

<StringArray>
['Y']
Length: 1, dtype: str

In [53]:
df.tartar.unique()

<StringArray>
['Y', 'N']
Length: 2, dtype: str

In [54]:
df = df.drop(columns=["oral"]) # tiene 1 solo valor

In [57]:
df.to_csv(PATH_PROJECT + "data/processed/dataset_merged_processed.csv", index=False)